const cartTypes = {
    "TOGGLE_CART_DROPDOWN": "TOGGLE_CART_DROPDOWN",
    "HIDE_CART_DROPDOWN": "HIDE_CART_DROPDOWN",
    "SHOW_CART_DROPDOWN": "SHOW_CART_DROPDOWN",
    "ADD_ITEM_TO_CART": "ADD_ITEM_TO_CART",
    "REMOVE_ITEM_FROM_CART":"REMOVE_ITEM_FROM_CART",
    "REMOVE_ITEM_FROM_CART_COMPLETELY":"REMOVE_ITEM_FROM_CART_COMPLETELY",
}

export default cartTypes; 