const shopActionTypes = {
    "FETCH_COLLECTIONS_START":"FETCH_COLLECTIONS_START",
    "FETCH_COLLECTIONS_SUCCESS":"FETCH_COLLECTIONS_SUCCESS",
    "FETCH_COLLECTIONS_FAILURE":"FETCH_COLLECTIONS_FAILURE",
    "FETCH_FEATURED_ITEMS_START":"FETCH_FEATURED_ITEMS_START",
    "FETCH_FEATURED_ITEMS_SUCCESS":"FETCH_FEATURED_ITEMS_SUCCESS",
    "FETCH_FEATURED_ITEMS_FAILURE":"FETCH_FEATURED_ITEMS_FAILURE",
    "FETCH_AUTOCOMPLETE_ITEMS_START":"FETCH_AUTOCOMPLETE_ITEMS_START",
    "FETCH_AUTOCOMPLETE_ITEMS_FAILURE":"FETCH_AUTOCOMPLETE_ITEMS_FAILURE",
    "FETCH_AUTOCOMPLETE_ITEMS_SUCCESS":"FETCH_AUTOCOMPLETE_ITEMS_SUCCESS",
}

export default shopActionTypes;