const shopActionTypes = {
    "FETCH_COLLECTION_START":"FETCH_COLLECTION_START",
    "FETCH_COLLECTION_SUCCESS":"FETCH_COLLECTION_SUCCESS",
    "FETCH_COLLECTION_FAILURE":"FETCH_COLLECTION_FAILURE",
    "FETCH_FEATURED_ITEMS_START":"FETCH_FEATURED_ITEMS_START",
    "FETCH_FEATURED_ITEMS_SUCCESS":"FETCH_FEATURED_ITEMS_SUCCESS",
    "FETCH_FEATURED_ITEMS_FAILURE":"FETCH_FEATURED_ITEMS_FAILURE",
}

export default shopActionTypes;