const cartTypes = {
    "TOGGLE_CART_DROPDOWN": "TOGGLE_CART_DROPDOWN",
    "HIDE_CART_DROPDOWN": "HIDE_CART_DROPDOWN",
    "SHOW_CART_DROPDOWN": "SHOW_CART_DROPDOWN",
    "ADD_ITEM_TO_CART": "ADD_ITEM_TO_CART",
    "REMOVE_ITEM_FROM_CART":"REMOVE_ITEM_FROM_CART",
    "REMOVE_ITEM_FROM_CART_COMPLETELY":"REMOVE_ITEM_FROM_CART_COMPLETELY",
    "ADD_NEW_BUY_NOW_ITEM":"ADD_NEW_BUY_NOW_ITEM",
    "ADD_BUY_NOW_ITEM":"ADD_BUY_NOW_ITEM",
    "REMOVE_BUY_NOW_ITEM":"REMOVE_BUY_NOW_ITEM",
}

export default cartTypes; 