const currentItemTypes = {"SET_CURRENT_ITEM_START":"SET_CURRENT_ITEM_START",
"SET_CURRENT_ITEM_FAILURE":"SET_CURRENT_ITEM_FAILURE",
"SET_CURRENT_ITEM_SUCCESS":"SET_CURRENT_ITEM_SUCCESS",

"FETCH_CURRENT_ITEM_START":"FETCH_CURRENT_ITEM_START",
"FETCH_CURRENT_ITEM_FAILURE":"FETCH_CURRENT_ITEM_FAILURE",
"FETCH_CURRENT_ITEM_SUCCESS":"FETCH_CURRENT_ITEM_SUCCESS",

"POST_REVIEW_START":"POST_REVIEW_START",
"POST_REVIEW_FAILURE":"POST_REVIEW_FAILURE",
"POST_REVIEW_SUCCESS":"POST_REVIEW_SUCCESS",};


export default currentItemTypes;
