const profileActionTypes = {
    "FETCH_CURRENT_PROFILE_START":"FETCH_CURRENT_PROFILE_START",
    "FETCH_CURRENT_PROFILE_FAILURE":"FETCH_CURRENT_PROFILE_FAILURE",
    "FETCH_CURRENT_PROFILE_SUCCESS":"FETCH_CURRENT_PROFILE_SUCCESS",

    "FETCH_SELLER_REVIEWS_START":"FETCH_SELLER_REVIEWS_START",
    "FETCH_SELLER_REVIEWS_FAILURE":"FETCH_SELLER_REVIEWS_FAILURE",
    "FETCH_SELLER_REVIEWS_SUCCESS":"FETCH_SELLER_REVIEWS_SUCCESS",
    
    "POST_REVIEW_SELLER_START":"POST_REVIEW_SELLER_START",
    "POST_REVIEW_SELLER_FAILURE":"POST_REVIEW_SELLER_FAILURE",
    "POST_REVIEW_SELLER_SUCCESS":"POST_REVIEW_SELLER_SUCCESS",

    "SET_CURRENT_PROFILE_START":"SET_CURRENT_PROFILE_START",
    "SET_CURRENT_PROFILE_FAILURE":"SET_CURRENT_PROFILE_FAILURE",
    "SET_CURRENT_PROFILE_SUCCESS":"SET_CURRENT_PROFILE_SUCCESS",
};


export default profileActionTypes; 