const userActionType = {
"FETCHING_USER_WITH_GOOGLE_SIGN_IN_START":"FETCHING_USER_WITH_GOOGLE_SIGN_IN_START",
"FETCHING_USER_WITH_GOOGLE_SIGN_IN_SUCCESS_":"FETCHING_USER_WITH_GOOGLE_SIGN_IN_SUCCESS_",
"FETCHING_USER_WITH_GOOGLE_SIGN_IN_FAILURE":"FETCHING_USER_WITH_GOOGLE_SIGN_IN_FAILURE",
"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_START":"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_START",
"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_SUCCESS_":"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_SUCCESS",
"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_FAILURE":"FETCHING_USER_WITH_EMAIL_PASSWORD_SIGN_IN_FAILURE",
"SIGN_IN_START":"SIGN_IN_START",
"SIGN_IN_SUCCESS":"SIGN_IN_SUCCESS",
"SIGN_IN_FAILURE":"SIGN_IN_FAILURE",
"SET_USER":"SET_USER",
"SET_UNSUBSCRIBER":"SET_UNSUBSCRIBER",
}

export default userActionType; 