const browseActionTypes = {
    "FETCH_ITEMS_START": "FETCH_ITEMS_START",
    "FETCH_ITEMS_FAILURE": "FETCH_ITEMS_FAILURE",
    "FETCH_ITEMS_SUCCESS": "FETCH_ITEMS_SUCCESS",

    "SET_CURRENT_ITEM":"SET_CURRENT_ITEM",
    
    "FETCH_CURRENT_ITEM_START":"FETCH_CURRENT_ITEM_START",
    "FETCH_CURRENT_ITEM_FAILURE":"FETCH_CURRENT_ITEM_FAILURE",
    "FETCH_CURRENT_ITEM_SUCCESS":"FETCH_CURRENT_ITEM_SUCCESS",

    "POST_REVIEW_START":"POST_REVIEW_START",
    "POST_REVIEW_FAILURE":"POST_REVIEW_FAILURE",
    "POST_REVIEW_SUCCESS":"POST_REVIEW_SUCCESS",

};


export default browseActionTypes; 