const browseActionTypes = {
    "FETCH_ITEMS_START": "FETCH_ITEMS_START",
    "FETCH_ITEMS_FAILURE": "FETCH_ITEMS_FAILURE",
    "FETCH_ITEMS_SUCCESS": "FETCH_ITEMS_SUCCESS",

    "SET_CURRENT_ITEM_START":"SET_CURRENT_ITEM_START",
    "SET_CURRENT_ITEM_FAILURE":"SET_CURRENT_ITEM_FAILURE",
    "SET_CURRENT_ITEM_SUCCESS":"SET_CURRENT_ITEM_SUCCESS",
    
    "FETCH_CURRENT_ITEM_START":"FETCH_CURRENT_ITEM_START",
    "FETCH_CURRENT_ITEM_FAILURE":"FETCH_CURRENT_ITEM_FAILURE",
    "FETCH_CURRENT_ITEM_SUCCESS":"FETCH_CURRENT_ITEM_SUCCESS",

    "POST_REVIEW_START":"POST_REVIEW_START",
    "POST_REVIEW_FAILURE":"POST_REVIEW_FAILURE",
    "POST_REVIEW_SUCCESS":"POST_REVIEW_SUCCESS",

    "FETCH_CURRENT_PROFILE_START":"FETCH_CURRENT_PROFILE_START",
    "FETCH_CURRENT_PROFILE_FAILURE":"FETCH_CURRENT_PROFILE_FAILURE",
    "FETCH_CURRENT_PROFILE_SUCCESS":"FETCH_CURRENT_PROFILE_SUCCESS",

    "FETCH_SELLER_REVIEWS_START":"FETCH_SELLER_REVIEWS_START",
    "FETCH_SELLER_REVIEWS_FAILURE":"FETCH_SELLER_REVIEWS_FAILURE",
    "FETCH_SELLER_REVIEWS_SUCCESS":"FETCH_SELLER_REVIEWS_SUCCESS",

    "SET_CURRENT_PROFILE":"SET_CURRENT_PROFILE",

};


export default browseActionTypes; 