const browseActionTypes = {
    "FETCH_ITEMS_START": "FETCH_ITEMS_START",
    "FETCH_ITEMS_FAILURE": "FETCH_ITEMS_FAILURE",
    "FETCH_ITEMS_SUCCESS": "FETCH_ITEMS_SUCCESS",

    "SET_CURRENT_ITEM":"SET_CURRENT_ITEM",
};


export default browseActionTypes; 